### ISSUE TITLE
String comparison to find build script

### ISSUE THREAD

**Issue by paralexm** [xenial-io/Xenial.BTool#1]
https://github.com/xenial-io/Xenial.BTool/blob/9ce64ce58ca7e9b84a8885bdac16bf64d0fb4fd4/Xenial.BTool/BuildLocator.cs#L48C1-L52C19

I think that comparison should be done with `StringComparison.OrdinalIgnoreCase` on any platform . We would want to find `build.sh` or `BUILD.sh` no? As long as the executor calls the file with the correct casing (which it does).

I can make the change if you want.

**Comment by biohazard999** [comment]
Sounds good to me. We also should check if b-tool works on Linux and Mac.
