### ISSUE TITLE
nuget.config file vs hardcoded in restore/deploy target

### ISSUE THREAD

**Issue by paralexm** [xenial-io/Xenial.BTool#3]
https://github.com/xenial-io/Xenial.BTool/blob/9ce64ce58ca7e9b84a8885bdac16bf64d0fb4fd4/build/Program.cs#L23C1-L24C25

When I tried to restore the project it failed because I have global nuget sources that require credentials. We could fix this by specifying the explicit nuget.org source in the `restore` target (like you did with the `deploy` target). Or we could add a basic `nuget.config` file in the project.

I will make a PR, just let me know which option you prefer.

**Comment by biohazard999** [comment]
Should add nuget.config.

Also need ci/CD I think
